name: dart_periphery
version: 0.8.16-beta
description:  >- 
  dart_periphery is a Dart port of the native c-periphery library for Linux Peripheral I/O (GPIO, LED, PWM, SPI, I2C, MMIO and Serial peripheral I/O).

homepage: https://github.com/pezi/dart_periphery
repository: https://github.com/pezi/dart_periphery
issue_tracker: https://github.com/pezi/dart_periphery/issues
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  system_info: ^1.0.0
  path: ^1.8.0
  # If you use `package:pedantic/pedantic.dart`, add a normal dependency.
  pedantic: ^1.11.0
  process: ^4.1.0

 
dev_dependencies:
  test: ^1.16.5
