name: dart_periphery
version: 0.7.0-beta
description: Dart port of the c-periphery library
homepage: https://github.com/pezi/dart_periphery
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  system_info: ^0.1.3
  path: ^1.7.0
 
dev_dependencies:
  test: ^1.5.3
